---
title: "I want to try..."
author: "Pratichhya Sharma"
date: "9 June 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Hi there! If you are here thinking that I might be an interesting personality then I am sorry I am not. I am neither a good writer nor a good eloquent. Today it was my last class scheduled for scientific writing and I remember on its first day Prof. Stefan Lang said, <b>“To learn how to write keep writing”</b>. So, here I am writing a blog with my not so good writing but great enthusiasm to share my feeling through my words. In both my personal and professional life, I learned a lot from many people. I cherish those learning but also, I fear my weakness.<br> Lessons from my experience have made me strong and weak at the same time. As I said, I don't know how to express what strong and weak at the same time mean to me. But I will try to express here what I am learning from not just geospatial domain but also from international committee. Thank you for your time. Be good Do good.
