---
title: "Geoinformatics meets Data Science "
author: "Pratichhya Sharma"
date: "6/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<style> body {text-align: justify; font-family: Times New Roman;
  font-size: 12pt;
}</style> <!-- Justify text. -->


As a part of my course work, I got an opportunity to participate in spring school organized by the Interfaculty Dept. of Geoinformatics – Z_GIS, University of Salzburg. Spring school was held from 7th-9th April 2021 in online mode where experts working in the field of Geoinformatics with Artificial Intelligence present their findings. Based on the introduction of the spring school I expected to gain insights and an overview of machine learning and artificial intelligence, methods and methodologies in combination with Geoinformatics.

The agenda for the school was well organized in a way that, on first day focus was done on data handling techniques followed by Sematic Clustering with LDA and Sentiment Analysis with BERT on the second day. The final day was dedicated in introducing Time Series Analysis with Recurrent Neural Networks. The participants were given a Python notebook that had previously been created by the experts, as well as the dataset for the practical sessions. A presentation entitled "geoAI: Intelligent Geospatial Analysis", presented the concept on how artificial intelligence is being used in geospatial domain. With the presentation I learned more about the advantages of geoAI, how it can impact us and how to use it for simple application such as social-media data analysis. 

With the realization of data handling as an essential task, a session was included to explain working with a database. Simple concepts on SQL were explained including, optimization methods and linkage with the spatial data. During the talk for Semantic Clustering with a statistical model LDA, tweets were analyzed for presenting hotspot analysis. The topic was new but interesting for me and hope I understood the process well enough. According to my understanding, unstructured text was processed by removing noises. Then multiple different algorithms were used for finding the text type as positive or negative by extracting the words and analyzing them. The spaCY library was used to extract entities in text. It was made clear that spaCy uses word embedding to determine the entity class of a word within the sentence syntax. The advantage of this approach is that it can return locations even with spelling errors. A disadvantage is possible false positives due to different sentence syntaxes.
Then goal for sentiment analysis was set, to determine if a text express positive, negative or neutral sentiment. In the presented application BERT model (Bidirectional Encoder Representation) was used to transform the words. The presenter highlighted the facts from their findings that BERT performed better as compared to widely used LSTM (Long-Short Term Memory). Further in the application, they used RoBERTa which is a robust approach, the only difference was RoBERT is longer pre-trained than the BERT network. The presentation on Recurrent and Convolution Neural Network (RNN) started with a clear differentiation between machine learning and deep learning. Then the focus was drawn on neural network for sequential data processing.

Overall, my spring school experience was positive, and I was able to meet the majority of my expectations. I appreciate the entire team for their effort and time. All of the presentations were straightforward and well-guided. They assisted me in expanding my expertise in geoinformatics and artificial intelligence. Thank you to the organizing committee for this opportunity and if you are interested in learning more about how geoinformatics meet data science I recommend you this spring school.

Thank you for your time and patience in reading this blog. Be good do good.
